// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27XwNdYL1uoA77lCHWUTbo1NJbRL7FMg',
    appId: '1:896148936121:web:d86f361effee1f418bd268',
    messagingSenderId: '896148936121',
    projectId: 'propertmanager-6fa5b',
    authDomain: 'propertmanager-6fa5b.firebaseapp.com',
    storageBucket: 'propertmanager-6fa5b.firebasestorage.app',
    measurementId: 'G-HR7ESWK8YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLxtj0S0ZiFE6YXs0uUfFW_0nvZq--CA',
    appId: '1:896148936121:android:5a0b7c02fa4ba23f8bd268',
    messagingSenderId: '896148936121',
    projectId: 'propertmanager-6fa5b',
    storageBucket: 'propertmanager-6fa5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpiokk_MdTf4LasWQOkhm2fSOSvR_C1o',
    appId: '1:896148936121:ios:398cf580d778bc498bd268',
    messagingSenderId: '896148936121',
    projectId: 'propertmanager-6fa5b',
    storageBucket: 'propertmanager-6fa5b.firebasestorage.app',
    iosBundleId: 'com.example.propertyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpiokk_MdTf4LasWQOkhm2fSOSvR_C1o',
    appId: '1:896148936121:ios:398cf580d778bc498bd268',
    messagingSenderId: '896148936121',
    projectId: 'propertmanager-6fa5b',
    storageBucket: 'propertmanager-6fa5b.firebasestorage.app',
    iosBundleId: 'com.example.propertyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27XwNdYL1uoA77lCHWUTbo1NJbRL7FMg',
    appId: '1:896148936121:web:bcfd050d783efcc68bd268',
    messagingSenderId: '896148936121',
    projectId: 'propertmanager-6fa5b',
    authDomain: 'propertmanager-6fa5b.firebaseapp.com',
    storageBucket: 'propertmanager-6fa5b.firebasestorage.app',
    measurementId: 'G-7YHRV1WPVD',
  );
}
